apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin-dashboard
          image: zopify-admin:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://api.zopify.local/api/v1"
